<?php
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

namespace Google\Service\WebSecurityScanner\Resource;

use Google\Service\WebSecurityScanner\ListScanConfigsResponse;
use Google\Service\WebSecurityScanner\ScanConfig;
use Google\Service\WebSecurityScanner\ScanRun;
use Google\Service\WebSecurityScanner\StartScanRunRequest;
use Google\Service\WebSecurityScanner\WebsecurityscannerEmpty;

/**
 * The "scanConfigs" collection of methods.
 * Typical usage is:
 *  <code>
 *   $websecurityscannerService = new Google\Service\WebSecurityScanner(...);
 *   $scanConfigs = $websecurityscannerService->scanConfigs;
 *  </code>
 */
class ProjectsScanConfigs extends \Google\Service\Resource
{
  /**
   * Creates a new ScanConfig. (scanConfigs.create)
   *
   * @param string $parent Required. The parent resource name where the scan is
   * created, which should be a project resource name in the format
   * 'projects/{projectId}'.
   * @param ScanConfig $postBody
   * @param array $optParams Optional parameters.
   * @return ScanConfig
   */
  public function create($parent, ScanConfig $postBody, $optParams = [])
  {
    $params = ['parent' => $parent, 'postBody' => $postBody];
    $params = array_merge($params, $optParams);
    return $this->call('create', [$params], ScanConfig::class);
  }
  /**
   * Deletes an existing ScanConfig and its child resources. (scanConfigs.delete)
   *
   * @param string $name Required. The resource name of the ScanConfig to be
   * deleted. The name follows the format of
   * 'projects/{projectId}/scanConfigs/{scanConfigId}'.
   * @param array $optParams Optional parameters.
   * @return WebsecurityscannerEmpty
   */
  public function delete($name, $optParams = [])
  {
    $params = ['name' => $name];
    $params = array_merge($params, $optParams);
    return $this->call('delete', [$params], WebsecurityscannerEmpty::class);
  }
  /**
   * Gets a ScanConfig. (scanConfigs.get)
   *
   * @param string $name Required. The resource name of the ScanConfig to be
   * returned. The name follows the format of
   * 'projects/{projectId}/scanConfigs/{scanConfigId}'.
   * @param array $optParams Optional parameters.
   * @return ScanConfig
   */
  public function get($name, $optParams = [])
  {
    $params = ['name' => $name];
    $params = array_merge($params, $optParams);
    return $this->call('get', [$params], ScanConfig::class);
  }
  /**
   * Lists ScanConfigs under a given project.
   * (scanConfigs.listProjectsScanConfigs)
   *
   * @param string $parent Required. The parent resource name, which should be a
   * project resource name in the format 'projects/{projectId}'.
   * @param array $optParams Optional parameters.
   *
   * @opt_param int pageSize The maximum number of ScanConfigs to return, can be
   * limited by server. If not specified or not positive, the implementation will
   * select a reasonable value.
   * @opt_param string pageToken A token identifying a page of results to be
   * returned. This should be a `next_page_token` value returned from a previous
   * List request. If unspecified, the first page of results is returned.
   * @return ListScanConfigsResponse
   */
  public function listProjectsScanConfigs($parent, $optParams = [])
  {
    $params = ['parent' => $parent];
    $params = array_merge($params, $optParams);
    return $this->call('list', [$params], ListScanConfigsResponse::class);
  }
  /**
   * Updates a ScanConfig. This method support partial update of a ScanConfig.
   * (scanConfigs.patch)
   *
   * @param string $name The resource name of the ScanConfig. The name follows the
   * format of 'projects/{projectId}/scanConfigs/{scanConfigId}'. The ScanConfig
   * IDs are generated by the system.
   * @param ScanConfig $postBody
   * @param array $optParams Optional parameters.
   *
   * @opt_param string updateMask Required. The update mask applies to the
   * resource. For the `FieldMask` definition, see https://developers.google.com
   * /protocol-buffers/docs/reference/google.protobuf#fieldmask
   * @return ScanConfig
   */
  public function patch($name, ScanConfig $postBody, $optParams = [])
  {
    $params = ['name' => $name, 'postBody' => $postBody];
    $params = array_merge($params, $optParams);
    return $this->call('patch', [$params], ScanConfig::class);
  }
  /**
   * Start a ScanRun according to the given ScanConfig. (scanConfigs.start)
   *
   * @param string $name Required. The resource name of the ScanConfig to be used.
   * The name follows the format of
   * 'projects/{projectId}/scanConfigs/{scanConfigId}'.
   * @param StartScanRunRequest $postBody
   * @param array $optParams Optional parameters.
   * @return ScanRun
   */
  public function start($name, StartScanRunRequest $postBody, $optParams = [])
  {
    $params = ['name' => $name, 'postBody' => $postBody];
    $params = array_merge($params, $optParams);
    return $this->call('start', [$params], ScanRun::class);
  }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ProjectsScanConfigs::class, 'Google_Service_WebSecurityScanner_Resource_ProjectsScanConfigs');
